### ISSUE TITLE
Can't pull JSON data

### ISSUE THREAD

**Issue by luquitared** [KimChoJapFan/Discord-Scraper#1] opened 2018-06-21 03:55 UTC
Hello there. Thank you for publishing your work. 
I am trying to get the script to pull JSON data but nothing happens when I run the script. I added my discord keys and the folder for the scraped data is generated by no files appears. No errors appear and the script terminates quickly. 
Thanks in advance :)

**Comment by KimChoJapFan** [comment] 2018-06-22 06:02
Which version are you using (the Python 2 or Python 3 version)?

**Comment by luquitared** [comment] 2018-06-24 03:00
I believe python3 but I will double check tomorrow.

**Comment by luquitared** [comment] 2018-06-25 18:54
I used both python 2.7 and 3. My selenium environment works correctly too because it does enter discord.

**Comment by luquitared** [comment] 2018-06-25 21:59
I used python3 and python2.7

**Comment by KimChoJapFan** [comment] 2018-06-25 22:39
Okay so you grabbed both versions and you ensured that you grabbed your Discord token as per the instructions from the README.md file (and I'm assuming that you also didn't put the quotes into the token)

So that can leave us with a couple of possibilities:

1. You attempted to grab data from a server/channel you didn't have permissions to view (those can't be grabbed unless you have the ability to view messages in said server/channel of course).

2. You attempted to grab data from personal messages instead of from a server (there's a different method for grabbing data from personal messages and I do plan on incorporating that into my upcoming release; although I did make an experimental branch where I did make some modifications to the python 3 version of the script to remove the requests dependency).

3. You made a typo in the token/channel id/server id or you got something mixed up (this could be an authentication issue which can be fixed by making sure that the token that you pasted into the script matches the token from the inspect element of the Discord site/app but without the double quotes).

If you've confirmed that it's none of these 3 possibilities then please report back and I'll delve further into this because I'm very certain that it's one of the 3 issues above because there's a lot of technical steps needed to get the information to get these scripts working and so that makes a bunch of possible points of error.

**Comment by luquitared** [comment] 2018-06-25 22:59
So I can successfully scrape files/photos, but I cannot scrape text. Is
there a way to do this?
Thank you

**Comment by luquitared** [comment] 2018-06-25 23:03
For example in self.query, is there a string I can use to query for just text messages in the channel?

**Comment by KimChoJapFan** [comment] 2018-06-27 05:11
In that case the scripts are looking through the attachments array which is where the images/videos are likely going to be.

Here's the JSON data of a regular (non-attachment) post:
`{
	"attachments": [],
	"tts": false,
	"embeds": [],
	"timestamp": "2018-06-26T14:12:20.272000+00:00",
	"mention_everyone": false,
	"id": "012345678911121314",
	"pinned": false,
	"edited_timestamp": null,
	"author": {
		"username": "Username",
		"discriminator": "1234",
		"id": "012345678911121314",
		"avatar": "md5 hash here"
	},
	"mention_roles": [],
	"content": "My Message Here",
	"channel_id": "012345678911121314",
	"mentions": [],
	"type": 0
},`

So I can point the script to look for jsonData['messages'][i]['content'] instead of traversing through the attachments area. This is faster than the original script and I can definitely implement this but I'll be putting these modifications in the experimental branch until I iron out all functions.

**Comment by KimChoJapFan** [comment] 2018-06-27 05:29
I was able to get the JSON data by making a simple search (for any word for instance) and I just watched the inspect element's network tab fill up with requests and I saw that the "search?" one was the one that had the JSON response to it which is what I used to make these scripts and to get that JSON value above.

The way it should be done is something like this:
`for messages in jsonData['messages']: for x in range(len(messages)): for content in messages[x]['content']: print(content)`

That should just print everything out into the command line but you can definitely experiment as I'm about to send the entire JSON output from Discord's search function:

`{
	"hit": true,
	"attachments": [
		{
			"url": "direct image url",
			"proxy_url": "alternate direct image url as a fallback",
			"filename": "image filename with extension",
			"width": image width in pixels (integer value),
			"height": image height in pixels (integer value),
			"id": "012345678910111213",
			"size": filesize in bytes (integer value)
		}
	],
	"tts": false,
	"embeds": [],
	"timestamp": "2018-06-26T14:20:00.029000+00:00",
	"mention_everyone": false,
	"id": "012345678910111213",
	"pinned": false,
	"edited_timestamp": null,
	"author": {
		"username": "Username",
		"discriminator": "1234",
		"id": "012345678910111213",
		"avatar": "md5 hash here"
	},
	"mention_roles": [],
	"content": "",
	"channel_id": "012345678910111213",
	"mentions": [],
	"type": 0
}`

I'm going to make some modifications to both the Python 2 and Python 3 versions of the script in the experimental branch to contain additional functions for scraping based on all of the parameters in the JSON results to make this script fully inclusive.

**Comment by luquitared** [comment] 2018-06-27 23:23
Awesome. I am not too sure what you mean by searching discord, but I would also like to download the entire JSON... very cool. I tried this:

`self.query  = 'has="search?"&has=video&include_nsfw=true'`

**Comment by KimChoJapFan** [comment] 2018-11-14 06:19
I'm closing this due to the update.

Hopefully the new version of the script works better than the older version.
Patches are to be expected in case the new scripts need some bugfixes.

**Closed** 2018-11-14 06:19 UTC
Labels: Master, Python 2, Python 3
